In [66]:
import pandas as pd
import numpy as np
import plotly.express as px

In [25]:
df = pd.read_csv('IndividualDetails.csv')
df.sample(5)

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
7056,7057,NaN,10/04/2020,NaN,NaN,NaN,Indore,Madhya Pradesh,NaN,Hospitalized,10/04/2020,Details awaited
6072,6073,NaN,09/04/2020,NaN,NaN,NaN,Mumbai,Maharashtra,NaN,Hospitalized,09/04/2020,Details awaited
468,468,NaN,23/03/2020,NaN,F,NaN,Thrissur,Kerala,India,Hospitalized,23/03/2020,Travelled from France
372,372,KA-P26,22/03/2020,22,M,Bhatkal,Uttara Kannada,Karnataka,India,Recovered,06/04/2020,Travelled from Dubai on Spicejet SG60 (21C)
1310,1310,NaN,30/03/2020,NaN,NaN,NaN,NaN,Telangana,NaN,Hospitalized,30/03/2020,Details awaited

In [14]:
df['current_status'].value_counts()

current_status
Hospitalized    8301
Recovered        139
Deceased          30
Migrated           1
Name: count, dtype: int64

In [28]:
total = df['current_status'].shape[0]
recoverd = df[df['current_status']=='Recovered'].shape[0]
Hospitalized = df[df['current_status']=='Hospitalized'].shape[0]
Deceased = df[df['current_status']=='Deceased'].shape[0]

30

In [34]:
new_df = df['detected_state'].value_counts().reset_index()
new_df.head()

   detected_state  count
0     Maharashtra   1761
1           Delhi   1069
2      Tamil Nadu    969
3       Rajasthan    700
4  Madhya Pradesh    529

In [50]:
new_df = df[df['current_status']=='Recovered']['detected_state'].value_counts().reset_index()
new_df

      detected_state  count
0             Kerala     58
1          Karnataka     39
2            Haryana     12
3      Uttar Pradesh      6
4         Tamil Nadu      6
5          Rajasthan      3
6        West Bengal      3
7              Delhi      2
8        Maharashtra      2
9     Andhra Pradesh      2
10         Telangana      1
11      Chhattisgarh      1
12       Uttarakhand      1
13           Gujarat      1
14  Himachal Pradesh      1
15           Manipur      1

In [35]:
df

,id,government_id,diagnosed_date,age,gender,detected_city,detected_district,detected_state,nationality,current_status,status_change_date,notes
0,0,KL-TS-P1,30/01/2020,20,F,Thrissur,Thrissur,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
1,1,KL-AL-P1,02/02/2020,NaN,NaN,Alappuzha,Alappuzha,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
2,2,KL-KS-P1,03/02/2020,NaN,NaN,Kasaragod,Kasaragod,Kerala,India,Recovered,14/02/2020,Travelled from Wuhan
3,3,DL-P1,02/03/2020,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,India,Recovered,15/03/2020,"Travelled from Austria, Italy"
4,4,TS-P1,02/03/2020,24,M,Hyderabad,Hyderabad,Telangana,India,Recovered,02/03/2020,"Travelled from Dubai to Bangalore on 20th Feb,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8467,8468,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8468,8469,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8469,8470,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8470,8471,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN
8471,8472,NaN,12/04/2020,NaN,NaN,NaN,NaN,West Bengal,NaN,Hospitalized,12/04/2020,NaN

In [60]:
age_data = pd.read_csv('AgeGroupDetails.csv')
age_data

   Sno AgeGroup  TotalCases Percentage
0    1      0-9          22      3.18%
1    2    10-19          27      3.90%
2    3    20-29         172     24.86%
3    4    30-39         146     21.10%
4    5    40-49         112     16.18%
5    6    50-59          77     11.13%
6    7    60-69          89     12.86%
7    8    70-79          28      4.05%
8    9     >=80          10      1.45%
9   10  Missing           9      1.30%

In [ ]:
data2 = pd.read_csv('covid_19_india.csv')

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,30/01/20,6:00 PM,Kerala,1,0,0,0,1
1,2,31/01/20,6:00 PM,Kerala,1,0,0,0,1
2,3,01/02/20,6:00 PM,Kerala,2,0,0,0,2
3,4,02/02/20,6:00 PM,Kerala,3,0,0,0,3
4,5,03/02/20,6:00 PM,Kerala,3,0,0,0,3
...,...,...,...,...,...,...,...,...,...
921,922,13/04/20,5:00 PM,Telengana,-,-,100,16,562
922,923,13/04/20,5:00 PM,Tripura,-,-,0,0,2
923,924,13/04/20,5:00 PM,Uttarakhand,-,-,5,0,35
924,925,13/04/20,5:00 PM,Uttar Pradesh,-,-,47,5,483
925,926,13/04/20,5:00 PM,West Bengal,-,-,29,7,152

In [80]:
px.line(data2,x='Date',y='Confirmed')