In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("smartphones - smartphones.csv")

In [3]:
df = data.copy()
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,"₹54,999",89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,"₹19,989",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,"₹16,499",75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,"₹14,999",81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,"₹24,999",82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

## Data Assessing

### Quality Issues

1. **model** - some brands are written diiferently like OPPO in model column `consistency`
2. **price** - has unneccesary '₹' `validity`
3. **price** - has ',' between numbers `validity`
4. **price** - phone Namotel has a price of 99 `accuracy`
5. **ratings** - missing values `completeness`
6. **processor** - has some incorrect values for some samsung phones(row # -642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002) `validity`
7. There is ipod on row 756 `validity`
8. **memory** - incorrect values in rows (441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002) `validity`
9. **battery** - incorrect values in rows(113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002) `validity`
10. **display** - sometimes frequency is not available `completeness`
11. **display** - incorrect values in rows(378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002) `validity`
12. certain phones are foldable and the info is scattered `validity`
13. **camera** - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
14. **camera** - problem with rows (100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016
) `validity`
15. **card** - sometimes contains info about os and camera `validity`
16. **os** - sometimes contains info about bluetooth and fm radio `validity`
17. **os** - issue with rows (324,378) `validity`
18. **os** - sometimes contains os version name like lollipop `consistency`
19. missing values in camera, card and os `completeness`
20. datatype  of price and rating is incorrect `validity`



### Tidiness Issues

1. **sim** - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
2. **ram** - can be split into 2 cols RAM and ROM
3. **processor** - can be split into processor name, cores and cpu speed.
4. **battery** - can be split into battery capacity, fast_charging_available
5. **display** - can be split into size, resolution_width, resolution_height and frequency
6. **camera** - can be split into front and rear camera
7. **card** - can be split into supported, extended_upto

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   str
 1   price      1020 non-null   str
 2   rating     879 non-null    float64
 3   sim        1020 non-null   str
 4   processor  1020 non-null   str
 5   ram        1020 non-null   str
 6   battery    1020 non-null   str
 7   display    1020 non-null   str
 8   camera     1019 non-null   str
 9   card       1013 non-null   str
 10  os         1003 non-null   str
dtypes: float64(1), str(10)
memory usage: 87.8 KB

In [5]:
df.describe()

           rating
count  879.000000
mean    78.258248
std      7.402854
min     60.000000
25%     74.000000
50%     80.000000
75%     84.000000
max     89.000000

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['price'] = df['price'].str.replace('₹','').str.replace(',','')
df['price'] = df['price'].astype('int')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   str
 1   price      1020 non-null   int64
 2   rating     879 non-null    float64
 3   sim        1020 non-null   str
 4   processor  1020 non-null   str
 5   ram        1020 non-null   str
 6   battery    1020 non-null   str
 7   display    1020 non-null   str
 8   camera     1019 non-null   str
 9   card       1013 non-null   str
 10  os         1003 non-null   str
dtypes: float64(1), int64(1), str(9)
memory usage: 87.8 KB

In [9]:
df.head()

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13

In [10]:
df.reset_index(inplace=True)

In [11]:
df['index'] = df['index']+2

In [12]:
df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [13]:
processor_rows = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))
memory_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016))

In [14]:
# rows in which atleast one column(processor,memory,battery,display,camera) has problem
total_rows = processor_rows | memory_rows | battery_rows | display_rows | camera_rows

In [15]:
# rows in which all the 5 columns processor,memory,battery,display,camera has problem
common_rows = processor_rows & memory_rows & battery_rows & display_rows & camera_rows

In [16]:
df[df['index'].isin(total_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
...,...,...,...,...,...,...,...,...,...,...,...,...
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
988,990,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [17]:
df[df['index'].isin(common_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
640,642,Nokia 105 Plus,1299,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
647,649,Motorola Moto A10,1339,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
657,659,Zanco Tiny T1,2799,NaN,Single Sim,"32 MB RAM, 32 MB inbuilt",200 mAh Battery,"0.49 inches, 64 x 32 px Display",No Rear Camera,No FM Radio,Bluetooth,NaN
665,667,itel it2163S,958,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1200 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
748,750,Nokia 400 4G,3290,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 64 GB",Bluetooth,Browser,NaN
757,759,Karbonn KU3i,995,NaN,Dual Sim,"52 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",Bluetooth,NaN
817,819,itel Magic X,2239,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"48 MB RAM, 128 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
927,929,Samsung Guru E1200,1685,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
930,932,iKall K88 Pro 4G,2099,NaN,"Dual Sim, 3G, 4G, VoLTE","48 MB RAM, 128 MB inbuilt",1800 mAh Battery,"2.4 inches, 240 x 360 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,Browser
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera

In [18]:
df = df[df['price']>3400]

In [19]:
df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
2,4,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Exynos 1330, Octa Core, 2.4 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 15W Fast Charging,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13
3,5,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12
4,6,Realme 10 Pro Plus,24999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Memory Card Not Supported,Android v13
...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1017,Motorola Moto Edge S30 Pro,34990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 68.2W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
1016,1018,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480+, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,"Memory Card Supported, upto 1 TB",Android v11
1017,1019,POCO X4 GT 5G (8GB RAM + 256GB),28990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8100, Octa Core, 2.85 GHz Processor","8 GB RAM, 256 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Memory Card Not Supported,Android v12
1018,1020,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12
1019,1021,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Octa Core Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12

In [20]:
df[df['index'].isin(common_rows)]
# they all are keypad phones not smart phones

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [21]:
df = df[~df['index'].isin(common_rows)]

In [22]:
df.shape[0]

988

In [23]:
# Now work on processor wala column
df[df['index'].isin(processor_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
857,859,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN

In [24]:
df = df[~df['index'].isin(processor_rows)]
df.shape[0]

987

In [25]:
# # Now work on ram  wala column
df[df['index'].isin(memory_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
582,584,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"

In [26]:
df.drop(582,inplace=True)

In [27]:
df[df['index'].isin(memory_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0

In [28]:
# Now work on ram  wala column
df[df['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,378,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
754,756,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [29]:
df.drop([376,754],inplace=True)

In [30]:
df[df['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [31]:
temp_df = df[df['index'].isin(battery_rows)]

In [32]:
x = temp_df.iloc[:,7:].shift(1,axis=1).values
x

array([[nan,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [nan, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [nan,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [nan, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [nan, '4.7 inches, 750\u2009x\u20091334\u2009px Display',
        '12\u2009MP Rear & 7\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v15'],
       [nan,
        '6.06 inches, 1170\u2009x\u20092532\u2009px, 120 Hz Display with Punch Hole',
        '50\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v15'],
       [nan,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14.0'],
       [nan, '6.1 inches, 750\u2009x\u20091580\u2009px Display',
        '12\u2009MP Rear & 10.8\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v16'],
       [nan,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP + 12\u2009MP Triple Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14.0'],
       [nan, '5.4 inches, 1080\u2009x\u20092340\u2009px Display',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14'],
       [nan,
        '6.1 inches, 1170\u2009x\u20092532\u2009px Display with Large Notch',
        '12\u2009MP + 12\u2009MP Dual Rear & 12\u2009MP Front Camera',
        'Memory Card Not Supported', 'iOS v14']], dtype=object)

In [33]:
df.loc[temp_df.index,temp_df.columns[7:]] = x

In [34]:
df[df['index'].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [35]:
# Now work on display wala column
df[df['index'].isin(display_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [36]:
# Now work on display wala column
df[df['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [37]:
df.drop([155,271,844],inplace=True)
# 155 271 844

In [38]:
df[df['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [39]:
temp_df = df[df['index'].isin(camera_rows)]

In [40]:
temp_df = temp_df[~temp_df['camera'].str.contains('MP')]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [41]:
df.loc[temp_df.index,'camera'] = temp_df['card'].values

In [42]:
df[df['index'].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",NaN,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",NaN,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [43]:
# now work with card column
df['card'].value_counts()

card
Memory Card Supported, upto 1 TB                                       171
Memory Card Not Supported                                              123
Android v12                                                            107
Memory Card Supported, upto 512 GB                                     105
Memory Card (Hybrid), upto 1 TB                                         91
Memory Card Supported                                                   89
Memory Card Supported, upto 256 GB                                      87
Android v13                                                             46
Android v11                                                             41
Memory Card (Hybrid)                                                    30
Memory Card (Hybrid), upto 256 GB                                       13
Memory Card (Hybrid), upto 512 GB                                       11
Android v10                                                             11
Memory Card Supported, upto 128 GB                                       6
Memory Card Supported, upto 2 TB                                         5
Memory Card Supported, upto 32 GB                                        4
Memory Card (Hybrid), upto 128 GB                                        3
Memory Card (Hybrid), upto 64 GB                                         3
50 MP Quad Rear & 16 MP Front Camera                                     2
12 MP + 12 MP Dual Rear & 10 MP Front Camera                             2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       2
64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                    2
50 MP + 8 MP Dual Rear & 32 MP Front Camera                              2
Android v9.0 (Pie)                                                       2
64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front Camera                    1
50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32 MP Dual Front Camera      1
50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                    1
Android v12.1                                                            1
50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera                        1
Memory Card Supported, upto 1000 GB                                      1
12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       1
64 MP + 13 MP + 12 MP Triple Rear & 32 MP Front Camera                   1
iOS v10                                                                  1
64 MP + 20 MP + 2 MP Triple Rear & Main Front Camera                     1
Android v10.0                                                            1
iOS v13                                                                  1
64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Front Camera                  1
50 MP + 16 MP + 13 MP Triple Rear & 32 MP Front Camera                   1
64 MP + 16 MP + 12 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front Camera                    1
50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Front Camera                  1
HarmonyOS v2.0                                                           1
108 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                   1
Memory Card (Hybrid), upto 2 TB                                          1
HarmonyOS                                                                1
48 MP Quad Rear Camera                                                   1
50 MP + 50 MP + 10 MP Triple Rear & 32 MP Front Camera                   1
Name: count, dtype: int64

In [44]:
# differnacing factort is Memory Card word

In [45]:
temp_df = df[df['card'].str.contains('MP')]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
69,71,Oppo Find N Fold,99990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front...,Android v12
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [46]:
df.loc[temp_df.index,'card'] = 'Memory Card Not Supported'

In [47]:
df[df['card'].str.contains('MP')]

Empty DataFrame
Columns: [index, model, price, rating, sim, processor, ram, battery, display, camera, card, os]
Index: []

In [48]:
df['card'].value_counts()

card
Memory Card Supported, upto 1 TB       171
Memory Card Not Supported              148
Android v12                            107
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Android v13                             46
Android v11                             41
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Android v10                             11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Android v9.0 (Pie)                       2
Android v12.1                            1
Memory Card Supported, upto 1000 GB      1
iOS v10                                  1
Android v10.0                            1
iOS v13                                  1
HarmonyOS v2.0                           1
Memory Card (Hybrid), upto 2 TB          1
HarmonyOS                                1
Name: count, dtype: int64

In [49]:
pd.set_option('display.max_rows',None)
temp_df = df[~df['card'].str.contains('Memory Card')]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
8,10,Nothing Phone 1,26749,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,11,OnePlus Nord 2T 5G,28999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
12,14,Xiaomi Redmi Note 12 Pro 5G,24762,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
17,19,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","16 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
18,20,OnePlus 10R 5G,32999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
20,22,OnePlus 11R,39999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 12 MP + 2 MP Triple Rear & 16 MP Front...,Android v13,Bluetooth
21,23,Vivo V25 Pro 5G,35999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4830 mAh Battery with 66W Fast Charging,"6.56 inches, 1080 x 2376 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
24,26,Vivo V26 Pro,42990,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 100W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
29,31,OnePlus 11 Pro,69999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Android v13,No FM Radio
37,39,Samsung Galaxy S22 Ultra 5G,91999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.8 inches, 1440 x 3080 px, 120 Hz Display wit...",108 MP Quad Rear & 40 MP Front Camera,Android v12,Bluetooth
39,41,OPPO Reno 9 5G,28499,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G, Octa Core, 2.4 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",64 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v13,No FM Radio
51,53,iQOO Neo 7 5G,29999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
58,60,Samsung Galaxy S23 Plus,84990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 45W Fast Charging,"6.6 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
60,62,Xiaomi Redmi Note 13 Pro 5G,17990,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 720, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Android v12,Bluetooth
61,63,Vivo S16,29990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v13,No FM Radio
65,67,Vivo S16 Pro,35499,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v13,No FM Radio
66,68,OnePlus 10 Pro 5G,60999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
73,75,OnePlus 10T,44999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 150W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
85,87,Motorola Edge 30 5G,22999,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G+, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",4020 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
91,93,OnePlus Ace Racing Edition 5G,22990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
93,95,Vivo X90 Pro Plus 5G,73999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.78 inches, 1440 x 3200 px, 120 Hz Display wi...",50.3 MP Quad Rear & 32 MP Front Camera,Android v13,No FM Radio
97,99,iQOO 11 5G,59999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.78 inches, 1440 x 3200 px, 144 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 16 MP Front...,Android v13,No FM Radio
102,104,Motorola Moto S30 Pro,23990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888+, Octa Core, 2.9 GHz Processor","8 GB RAM, 128 GB inbuilt",4400 mAh Battery with 68W Fast Charging,"6.55 inches, 1080 x 2460 px, 144 Hz Display wi...",50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
106,108,Vivo V27 Pro,43999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,Android v13,No FM Radio
107,109,Samsung Galaxy S22 5G,49999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP Fron...,Android v12,Bluetooth
109,111,OnePlus 10R 5G (12GB RAM + 256GB),36999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
110,112,Tecno Phantom X2,39999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 256 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.8 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
112,114,Xiaomi Redmi K50i 5G,22999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8100, Octa Core, 2.85 GHz Processor","6 GB RAM, 128 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
115,117,OPPO Reno8 5G,29340,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
119,121,Samsung Galaxy S23,70990,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
120,122,Motorola Edge 30 Pro 5G,34999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 68W Fast Charging,"6.7 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 60 MP Front...,Android v12,No FM Radio
121,123,OnePlus Nord 2T (12GB RAM + 256GB),33900,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
133,135,Nothing Phone 1 (8GB RAM + 256GB),28249,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
139,141,iQOO Neo 6 5G,28999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
141,143,OPPO Reno 9 Pro 5G,39999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","16 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v13,No FM Radio
146,148,iQOO 7,24990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4400 mAh Battery with 66W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
163,165,Oppo Reno 10 Pro Plus,58990,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.73 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP Quad Rear & 32 MP Front Camera,Android v13,No FM Radio
168,170,iQOO 9 SE 5G,30990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 66W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front...,Android v12,No FM Radio
170,172,Letv Y1 Pro,5499,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T310, Quad Core, 2 GHz Processor","4 GB RAM, 32 GB inbuilt",4000 mAh Battery,"6.54 inches, 720 x 1560 px Display with Small ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,Android v11,No FM Radio
183,185,Motorola Moto X40,39999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4600 mAh Battery with 125W Fast Charging,"6.7 inches, 1080 x 2400 px, 165 Hz Display",50 MP + 50 MP + 12 MP Triple Rear & 60 MP Fron...,Android v13,No FM Radio
186,188,OnePlus Nord 3 5G,27999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 128 GB inbuilt",4200 mAh Battery with 120W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front...,Android v11,No FM Radio
189,191,LeEco S1 Pro,10999,65.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T7150, Quad Core, 1.8 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.5 inches, 720 x 1600 px Display with Small N...",13 MP + Depth Sensor Dual Rear & 5 MP Front Ca...,Android v11,No FM Radio
196,198,OPPO Reno 8 Pro House of Dragon Edition,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100-Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
202,204,Motorola Edge 30 Ultra,54999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4610 mAh Battery with 125W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",200 MP + 50 MP + 12 MP Triple Rear & 60 MP Fro...,Android v12,No FM Radio
203,205,Xiaomi 13 Ultra 5G,71999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.6 inches, 1440 x 3200 px, 120 Hz Display wit...",108 MP Quad Rear & 32 MP Front Camera,Android v12,No FM Radio
206,208,Nothing Phone 1 (12GB RAM + 256GB),35999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
209,211,Xiaomi Redmi Note 12 Pro (8GB RAM + 256GB),27994,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
211,213,Vivo V25 Pro (12GB RAM + 256GB),39999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1300, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4830 mAh Battery with 66W Fast Charging,"6.56 inches, 1080 x 2376 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
215,217,Honor X9a,27999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 695, Octa Core, 2.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5100 mAh Battery with 40W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
216,218,Google Pixel 7 Pro 5G,81999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor G2, Octa Core, 2.85 GHz Processor","12 GB RAM, 128 GB inbuilt",5000 mAh Battery with 30W Fast Charging,"6.7 inches, 1440 x 3120 px, 120 Hz Display wit...",50 MP + 48 MP + 12 MP Triple Rear & 10.8 MP Fr...,Android v13,No FM Radio
220,222,Xiaomi Redmi K60,29990,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 67W Fast Charging,"6.67 inches, 1440 x 3200 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
223,225,Motorola Edge 30 5G (8GB RAM + 128GB),24999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G+, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",4020 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
228,230,Realme GT Neo 3T,24999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 870, Octa Core, 3.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
229,231,OPPO Reno 8 Pro 5G,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100-Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
230,232,OnePlus 10 Pro 5G (12GB RAM + 256GB),65499,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
231,233,iQOO 11 Pro 5G,58990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 200W Fast Charging,"6.78 inches, 1440 x 3200 px, 144 Hz Display wi...",50 MP + 50 MP + 13 MP Triple Rear & 16 MP Fron...,Android v13,No FM Radio
244,246,Google Pixel 7 5G,53100,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor G2, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",4355 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2400 px, 90 Hz Display with...",50 MP + 12 MP Dual Rear & 10.8 MP Front Camera,Android v13,No FM Radio
249,251,Nubia Red Magic 8 Pro 5G,46990,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.8 inches, 1116 x 2480 px, 120 Hz Display",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
251,253,Tecno Phantom X2 Pro,49999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","12 GB RAM, 256 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.8 inches, 1080 x 2400 px, 120 Hz Display wit...",50 MP + 50 MP + 13 MP Triple Rear & 32 MP Fron...,Android v12,Bluetooth
257,259,Samsung Galaxy S22 Plus 5G,64449,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 45W Fast Charging,"6.6 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP Fron...,Android v12,Bluetooth
258,260,Vivo U3x,8990,71.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480 , Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.58 inches, 1080 x 2408 px, 90 Hz Display wit...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v11,No FM Radio

In [50]:
df.loc[temp_df.index,'os'] = temp_df['card'].values

In [51]:
df.loc[temp_df.index,'card'] = 'Memory Card Not Supported'

In [52]:
df['card'].value_counts()

card
Memory Card Not Supported              361
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card Supported, upto 1000 GB      1
Memory Card (Hybrid), upto 2 TB          1
Name: count, dtype: int64

In [53]:
df['os'].value_counts()

os
Android v12                           394
Android v11                           274
Android v13                            91
Android v10                            69
Android v9.0 (Pie)                     29
Android v10.0                          23
iOS v16                                15
iOS v15                                12
Android v8.1 (Oreo)                    10
iOS v14                                 6
Memory Card Not Supported               6
iOS v13                                 4
Android v11.0                           4
Android v8.0 (Oreo)                     4
iOS v15.0                               3
Android v12.1                           2
Memory Card Supported, upto 256 GB      2
Android v5.1.1 (Lollipop)               2
Memory Card (Hybrid), upto 2 TB         2
iOS v14.0                               2
Harmony v2.0                            2
Memory Card (Hybrid), upto 256 GB       2
HarmonyOS v2.0                          2
Android v6.0 (Marshmallow)              2
EMUI v12                                2
HarmonyOS v2                            1
iOS v13.0                               1
iOS v12.3                               1
iOS v17                                 1
Android v4.4.2 (KitKat)                 1
Android v5.1 (Lollipop)                 1
Hongmeng OS v3.0                        1
Bluetooth                               1
Pragati OS (Powered by Android)         1
iOS v10                                 1
Memory Card (Hybrid)                    1
RTOS (Series 30+)                       1
Hongmeng OS v4.0                        1
HarmonyOS                               1
Android v7.1 (Nougat)                   1
Android                                 1
Android v9 (Pie)                        1
Name: count, dtype: int64

In [54]:
temp_df = df[df['os'].str.contains('Memory Card')]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card Not Supported,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"

In [55]:
temp_df = temp_df[temp_df['os'].str.contains('B')]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"

In [56]:
df.loc[temp_df.index,'card'] = temp_df['os'].values

In [57]:
temp_df = df[df['os'].str.contains('Memory Card')]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB","Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB","Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card Not Supported,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB","Memory Card (Hybrid), upto 2 TB"
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB","Memory Card (Hybrid), upto 256 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB","Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB","Memory Card (Hybrid), upto 256 GB"

In [58]:
df.loc[temp_df.index,'os'] = np.nan

In [59]:
temp_df = df[df['os'].str.contains('Bluetooth')]
df.loc[temp_df.index,'os'] = np.nan

In [60]:
df['os'].value_counts()

os
Android v12                        394
Android v11                        274
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
iOS v13                              4
Android v11.0                        4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
Android v12.1                        2
Android v5.1.1 (Lollipop)            2
iOS v14.0                            2
Harmony v2.0                         2
HarmonyOS v2.0                       2
Android v6.0 (Marshmallow)           2
EMUI v12                             2
HarmonyOS v2                         1
iOS v13.0                            1
iOS v12.3                            1
iOS v17                              1
Android v4.4.2 (KitKat)              1
Android v5.1 (Lollipop)              1
Hongmeng OS v3.0                     1
Pragati OS (Powered by Android)      1
iOS v10                              1
RTOS (Series 30+)                    1
Hongmeng OS v4.0                     1
HarmonyOS                            1
Android v7.1 (Nougat)                1
Android                              1
Android v9 (Pie)                     1
Name: count, dtype: int64

In [61]:
brand_names = df['model'].str.split(' ').str.get(0)
brand_names

0         OnePlus
1         OnePlus
2         Samsung
3        Motorola
4          Realme
5         Samsung
6           Apple
7          Xiaomi
8         Nothing
9         OnePlus
10         Realme
11           Oppo
12         Xiaomi
13           Vivo
14        Samsung
15          Apple
16           Vivo
17           OPPO
18        OnePlus
19           Vivo
20        OnePlus
21           Vivo
22           Poco
23         Xiaomi
24           Vivo
25        Samsung
26        OnePlus
27          Apple
28           Vivo
29        OnePlus
30         Realme
31           Poco
32           Vivo
33          Apple
34        Samsung
35        Samsung
36           Oppo
37        Samsung
38         Xiaomi
39           OPPO
40        OnePlus
41         Xiaomi
42       Motorola
43         Realme
44           Vivo
45        Samsung
46         Xiaomi
47         Realme
48           Vivo
49        Samsung
50        Samsung
51           iQOO
52            Jio
53       Motorola
54         Realme
55         Realme
56          Apple
57         Xiaomi
58        Samsung
59       Motorola
60         Xiaomi
61           Vivo
62        Samsung
63           Vivo
64           Poco
65           Vivo
66        OnePlus
67         Xiaomi
68        Samsung
69           Oppo
70           OPPO
71           Vivo
72           iQOO
73        OnePlus
74         Xiaomi
75         Gionee
76          Apple
77           OPPO
78        Samsung
79         Xiaomi
80       Motorola
81        Samsung
82         Realme
83           Vivo
84        Samsung
85       Motorola
86        Samsung
87           OPPO
88         Xiaomi
89        Samsung
90           Vivo
91        OnePlus
92       Motorola
93           Vivo
94         Realme
95         Realme
96           OPPO
97           iQOO
98           Vivo
99           Vivo
100         Apple
101        Xiaomi
102      Motorola
103        Realme
104          OPPO
105        Xiaomi
106          Vivo
107       Samsung
108          Vivo
109       OnePlus
110         Tecno
111         Apple
112        Xiaomi
113       Samsung
114        Xiaomi
115          OPPO
116       Samsung
117          iQOO
118         Tesla
119       Samsung
120      Motorola
121       OnePlus
122        Google
123       Infinix
124       Samsung
125          Vivo
126      Motorola
127       OnePlus
128       Samsung
129        Google
130        Xiaomi
131        Xiaomi
132      Motorola
133       Nothing
134          Poco
135        Xiaomi
136         Apple
137        Realme
138          OPPO
139          iQOO
140          iQOO
141          OPPO
142          Poco
143           Jio
144       OnePlus
145       Samsung
146          iQOO
147       Samsung
148        Xiaomi
149         Apple
150        Xiaomi
151      Motorola
152         Apple
153          Oppo
154       Infinix
156        Realme
157          OPPO
158        Realme
159          Oppo
160        Realme
161          Cola
162         Apple
163          Oppo
164          Vivo
165       Samsung
166        Xiaomi
167        Realme
168          iQOO
169       Infinix
170          Letv
171        Xiaomi
172        Realme
173          OPPO
174         Apple
175          iQOO
176        Xiaomi
177        Realme
178          Vivo
179          Vivo
180          POCO
181       Infinix
182         Tecno
183      Motorola
184       Samsung
185        Realme
186       OnePlus
187      Motorola
188         iKall
189         LeEco
190        Realme
191        Duoqin
192       Samsung
193         Nokia
194      Motorola
195        Realme
196          OPPO
197       OnePlus
198          Poco
199       Samsung
200          OPPO
201       Samsung
202      Motorola
203        Xiaomi
204      Motorola
205          Poco
206       Nothing
207       Samsung
208         Tecno
209        Xiaomi
210         Apple
211          Vivo
212        Realme
213        Realme
214          Lava
215         Honor
216        Google
217         Tecno
218          Vivo
219       Samsung
220        Xiaomi
221        Realme
222        Realme
223      Motorola
224        Xiaomi
225          Vivo
226          POCO
227        Realme
228        Realme
229          OPPO
230       OnePlus
231          iQOO
232          Vivo
233        Xiaomi
234          OPPO
235          Vivo
236        Xiaomi
237          Vivo
238          OPPO
239          Vivo
240        Xiaomi
241          OPPO
242       Samsung
243          Vivo
244        Google
245        Xiaomi
246          OPPO
247         Apple
248      Motorola
249         Nubia
250      Motorola
251         Tecno
252       Infinix
253          iQOO
254        Xiaomi
255          OPPO
256       Samsung
257       Samsung
258          Vivo
259      Motorola
260          Poco
261         Tecno
262          POCO
263         Apple
264       Samsung
265       Infinix
266          OPPO
267       OnePlus
268         Redmi
269       Nothing
270       Samsung
272        Google
273       Infinix
274        Xiaomi
275        Xiaomi
276        Xiaomi
277         Apple
278         Tecno
279        Realme
280          Asus
281          Vivo
282         Apple
283        Xiaomi
284          iQOO
285       Samsung
286        Xiaomi
287        Xiaomi
288       Infinix
289       Infinix
290         Apple
291       Samsung
292          Poco
293        Xiaomi
294        Realme
295       Samsung
296      Motorola
297          OPPO
298        Xiaomi
299        Xiaomi
300          Vivo
301        Xiaomi
302        Realme
303      Motorola
304        Xiaomi
305        Xiaomi
306       Samsung
307         Apple
308       OnePlus
309       Samsung
310          OPPO
311       OnePlus
312       Samsung
313       Samsung
314      Motorola
315          itel
316          Vivo
317       Samsung
318          POCO
319         Honor
320          iQOO
321       Samsung
322        Royole
323         Apple
324       Samsung
325         Tecno
326        Google
327        Xiaomi
328       Samsung
329       Infinix
330          Vivo
331          OPPO
332          iQOO
333       Samsung
334        Realme
335          Poco
336       Infinix
337       Samsung
338      Motorola
339       OnePlus
340        Xiaomi
341        Xiaomi
342         Tecno
343       Samsung
344          POCO
345       OnePlus
346         Apple
347          Oppo
348          Vivo
349      Motorola
350      Motorola
351        Xiaomi
352           Jio
353          Vivo
354        Xiaomi
355        Realme
356          Vivo
357          OPPO
358        Xiaomi
359          Poco
360        Realme
361        Xiaomi
362          iQOO
363         Apple
364       Samsung
365          OPPO
366       OnePlus
367         Tecno
368       Samsung
369        Xiaomi
370          Sony
371          Vivo
372          Poco
373       Samsung
374        Google
375       Samsung
377        Realme
378          OPPO
379        Realme
380       Samsung
381       Samsung
382          Vivo
383          Letv
384         Tecno
385          iQOO
386          Vivo
387        Realme
388       Samsung
389        Realme
390        Realme
391          OPPO
392          OPPO
393       Samsung
394       Oukitel
395        Realme
396        Xiaomi
397       Samsung
398        Xiaomi
399          itel
401        Realme
402         Apple
403          Poco
404       Samsung
405        Realme
406        Xiaomi
407          Vivo
408          OPPO
409        Xiaomi
410          Asus
411          Oppo
412        Realme
413       Samsung
414       OnePlus
415        Xiaomi
416          OPPO
417        Realme
418        Xiaomi
419         Redmi
420         Apple
421      Motorola
422      Motorola
423        Xiaomi
424         Honor
425       OnePlus
426          Vivo
427          OPPO
428        Xiaomi
429         Nokia
430        Xiaomi
431         Vertu
432       Samsung
433         Tecno
434          Poco
435           BLU
436          OPPO
437      Motorola
438        Xiaomi
439         Apple
440       Samsung
441          Poco
442        Xiaomi
443       Samsung
444      Motorola
445          Asus
446        Xiaomi
447       Infinix
448         Apple
449        Realme
450       Infinix
451          Vivo
452          Vivo
453         Tecno
454       Samsung
455         Redmi
456          Asus
457          Sony
458          iQOO
459         Tecno
460        Xiaomi
461       Samsung
462        Xiaomi
463          OPPO
464         Nubia
465       Samsung
466         Nokia
467       Infinix
468          Vivo
469          OPPO
470        Xiaomi
471        Realme
472       Infinix
474       Samsung
475       Samsung
476        Xiaomi
477          Vivo
478           Lyf
479      Motorola
480         Tecno
481          Itel
482          Vivo
483        Huawei
484       Samsung
485          iQOO
486         Nokia
487          Sony
488          Vivo
489          Sony
490         Tecno
491        Huawei
492          Vivo
493         Nubia
494      Motorola
495          iQOO
496       Samsung
497          POCO
498        Realme
499          Vivo
500         Honor
501        Xiaomi
502        Realme
503      Motorola
504       Samsung
505       OnePlus
506        Google
507        Xiaomi
508         Honor
509        Realme
510          Vivo
511       Samsung
512       Samsung
513        Realme
514          POCO
515        Google
516       OnePlus
517        Xiaomi
518       Samsung
519          Oppo
520          Vivo
521          iQOO
522          OPPO
523        Realme
524          Vivo
525      Motorola
526        Realme
527         Apple
528          Vivo
529       Samsung
530          Vivo
531        Xiaomi
534       OnePlus
535        Google
536         Nokia
537       Infinix
538          Poco
539        Xiaomi
540           ZTE
541        Xiaomi
542          OPPO
543        Huawei
544       Samsung
545        Lenovo
546          Vivo
547         Nokia
548        Realme
549        Realme
550         Nokia
552          Poco
553        Xiaomi
554          iQOO
555        Realme
556       Samsung
557        Xiaomi
558      Motorola
559       OnePlus
560          OPPO
561          Poco
562          OPPO
563          POCO
564        Realme
565          Asus
566        Realme
567       Samsung
568         Nubia
569       Samsung
570            LG
571        Xiaomi
572       Samsung
574          Vivo
576       Samsung
577          Oppo
578          Oppo
579          OPPO
580         Nokia
581          OPPO
583      Motorola
584          Oppo
585          iQOO
586         Nokia
587       Samsung
588          OPPO
589        Xiaomi
590         Tecno
591        Realme
592        Xiaomi
593          iQOO
594          iQOO
595        Realme
596        Xiaomi
597           Jio
598        Xiaomi
599        Xiaomi
600          Vivo
601       Samsung
602          Vivo
603        Realme
604       OnePlus
605       Samsung
606         Apple
607         Apple
609          Sony
610       Samsung
612        Xiaomi
613       Oukitel
614          Vivo
615          Poco
616        Xiaomi
617        Realme
618          Vivo
619        Xiaomi
620          Lava
621        Realme
622          OPPO
623          POCO
624        Realme
625          OPPO
626          Vivo
627         Nokia
628         Apple
629          Sony
630      Motorola
631       Samsung
632       Samsung
633        Xiaomi
634        Realme
635        Realme
636         Apple
637          iQOO
638         Tecno
639       OnePlus
641       Samsung
642          POCO
643        Xiaomi
644          Vivo
646       Samsung
648          Vivo
649        Huawei
650      Micromax
651          Asus
652        Realme
653        Realme
654          OPPO
655        Xiaomi
656         Apple
658          Letv
659       OnePlus
660          Vivo
661          OPPO
662          Vivo
663       Infinix
664        Realme
666          itel
667          OPPO
668        Xiaomi
669         Honor
670         Tecno
671       Infinix
672        Realme
673       Samsung
674         Tecno
675        Xiaomi
676        Xiaomi
677        Xiaomi
678        Xiaomi
679        Xiaomi
680            LG
681      Motorola
682            LG
683       Samsung
684       Samsung
686          iQOO
687       Samsung
688          Vivo
689          Vivo
690          itel
691        Xiaomi
692          Poco
693          OPPO
694       Samsung
695       Infinix
696         Honor
697       Infinix
698          Sony
700         Nubia
701         Nokia
702        Xiaomi
703          Oppo
704         Apple
705          Vivo
706          OPPO
707       Samsung
708          OPPO
709          OPPO
710       OnePlus
711        Gionee
712          Poco
713          OPPO
714      Motorola
715       Samsung
716       Samsung
717          Vivo
718          Vivo
719          Vivo
720          Vivo
721          Asus
722      Motorola
723        Xiaomi
724        Huawei
725        Realme
726        Huawei
727          iQOO
728         Apple
729       Infinix
730         Tecno
731          Oppo
732          Vivo
733        Xiaomi
734        Huawei
735         Tecno
736        Huawei
737        Xiaomi
738         Nokia
739        Realme
740          OPPO
741      Motorola
742          Oppo
743          Poco
744          itel
745          Vivo
746        Xiaomi
747          Vivo
749       Samsung
750          Vivo
751          Oppo
752        Realme
753          Vivo
755        Xiaomi
756          Poco
758         iKall
759        Xiaomi
760          Vivo
761         Honor
762         Apple
763         Tecno
764         Apple
765        Google
766          Vivo
767      Motorola
768      Motorola
769          Vivo
770        Realme
771          Vivo
772         Honor
773       Samsung
774       Samsung
775          Vivo
776        Xiaomi
777          Oppo
778         Tecno
779          Vivo
780        Xiaomi
781         Apple
782          Vivo
783          Vivo
784       Samsung
785        Xiaomi
786      Micromax
787       Samsung
788          OPPO
789        Xiaomi
790        Xiaomi
791        Realme
792          OPPO
793          Oppo
794          itel
795        Xiaomi
796       Samsung
797          POCO
798       Samsung
799        Realme
800        Huawei
801          Vivo
802          Vivo
803          Vivo
804          Vivo
805       Samsung
806        Realme
807          Vivo
808       Samsung
809         Leitz
810        Xiaomi
811       Infinix
812        Realme
813         Apple
814         Apple
815        Xiaomi
816        Xiaomi
818         Nokia
819       OnePlus
820         Tecno
821        Realme
822        Xiaomi
823          OPPO
824       Infinix
825       Samsung
826       Samsung
827          Vivo
828          Poco
829       Infinix
830       Samsung
831          Vivo
832        Xiaomi
833        Xiaomi
834        Realme
836          Vivo
837          Vivo
838        Gionee
839        Xiaomi
840         Apple
841       Infinix
842        Realme
843        Xiaomi
845        Xiaomi
847        Realme
848        Xiaomi
849        Lenovo
850       Samsung
851        Realme
853         Apple
854        Xiaomi
855        Realme
856       Samsung
858          Oppo
859          Oppo
860          Sony
861          Vivo
862        Huawei
863          Vivo
864          Vivo
865        Xiaomi
866        Xiaomi
867      Motorola
868        Google
869       Samsung
870       Samsung
871        Huawei
872        Xiaomi
874        Doogee
875        Huawei
876          iQOO
877          Vivo
878          Poco
879         Nokia
880         Tecno
883          Vivo
884        Huawei
885        Huawei
886       Samsung
887       Infinix
888       OnePlus
889        Realme
890       OnePlus
891          iQOO
892        Xiaomi
893          Oppo
894        Royole
895         Tecno
896         Tecno
897         Tecno
898        Realme
899          Sony
900        Realme
901         Tecno
902          Poco
903      Motorola
904       OnePlus
905        Realme
906        Realme
907          Itel
908       Samsung
909          Oppo
910       OnePlus
911       Samsung
912       OnePlus
913         Apple
914         Apple
915          OPPO
916        Xiaomi
918          Oppo
919        Realme
920       Samsung
921        Xiaomi
922        Xiaomi
923        Realme
924          OPPO
926           Lyf
928         Apple
929          Vivo
931          Lava
933         Tecno
934          OPPO
935      Motorola
936        Xiaomi
937       Infinix
938         Tecno
939           ZTE
940         Honor
941        Xiaomi
942           TCL
943       Samsung
944       Nothing
945      Motorola
946       OnePlus
947        Realme
948       Samsung
949       Samsung
950       Infinix
951          POCO
952          iQOO
953          Vivo
954          Vivo
955          Oppo
956         Tecno
957          iQOO
958       Infinix
959        Xiaomi
960       Samsung
961         Apple
962         Nubia
963      Micromax
964         Nokia
965          Vivo
966          Oppo
967          Poco
968         Honor
969          OPPO
970        Realme
971          iQOO
972        Realme
973       Samsung
974        Realme
975        Google
976       Samsung
977       Samsung
978       Samsung
979        Xiaomi
980          Vivo
981          OPPO
982        Realme
983          itel
984        Realme
985        Xiaomi
986          Vivo
987       OnePlus
989         Sharp
990        Huawei
991       Samsung
992        Realme
993        Huawei
994       Samsung
995       Samsung
996          Vivo
997          Poco
998     Blackview
999         Honor
1001         OPPO
1002       Doogee
1003         Lava
1004     Motorola
1005        iKall
1006      Oukitel
1007       Xiaomi
1008     Motorola
1009       Xiaomi
1010       Realme
1011         Oppo
1012         itel
1013       Google
1014         Vivo
1015     Motorola
1016        Honor
1017         POCO
1018     Motorola
1019      Samsung
Name: model, dtype: object

In [62]:
pd.reset_option('display.max_rows')
df.insert(1,'brand_name',brand_names)

In [63]:
df['brand_name'] = df['brand_name'].str.lower()

In [64]:
simtype = df['sim'].str.split(',').str.get(0)
df.insert(6,'sim_type',simtype)

In [65]:
has_3g = df['sim'].str.contains('3G')
df.insert(7,'has_3G',has_3g)

has_4g = df['sim'].str.contains('4G')
df.insert(8,'has_4G',has_4g)

has_5g = df['sim'].str.contains('5G')
df.insert(9,'has_5G',has_5g)

has_nfc = df['sim'].str.contains('NFC')
df.insert(10,'has_nfc',has_nfc)

has_irblaster = df['sim'].str.contains('IR Blaster')
df.insert(11,'has_irblaster',has_irblaster)

In [66]:
processor_name = df['processor'].str.split(',').str.get(0)
df.insert(13,'processor_name',processor_name)

num_cores = df['processor'].str.split(',').str.get(1)
df.insert(14,'num_cores',num_cores)

In [67]:
processor_speed = df['processor'].str.split(',').str.get(2)
df.insert(15,'processor_speed',processor_speed)

In [68]:
# pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)
# pd.reset_option('display.max_rows')
# pd.reset_option('display.max_columns')
# df

In [69]:
# acuuracy error snapdragon ki jgah ek row me sanpdragon tha
temp_df = df[df['processor_name']=='Sanpdragon']
df.loc[temp_df.index,'processor_type'] = 'Snapdragon 680'

In [70]:
# processor_type has validation issue means has coretype values
temp_df = df[df['processor_name'].str.contains('Core')]
temp_df

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,num_cores,processor_speed,ram,battery,display,camera,card,os,processor_type
118,120,tesla,Tesla Pi Phone,69999,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"16 GB RAM, 512 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,Android v13,NaN
143,145,jio,Jio Phone 3,4499,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.4 GHz Processor",Quad Core,1.4 GHz Processor,NaN,"2 GB RAM, 64 GB inbuilt",2800 mAh Battery,"5 inches, 720 x 1280 px Display",5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v8.1 (Oreo),NaN
188,190,ikall,iKall Z19 Pro,8099,60.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.6 GHz Processor",Quad Core,1.6 GHz Processor,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.5 inches, 720 x 1600 px Display with Water D...",13 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",Android v11.0,NaN
201,203,samsung,Samsung Galaxy A13,14450,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 2 GHz Processor",Octa Core,2 GHz Processor,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px Display with Water ...",50 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12,NaN
309,311,samsung,Samsung Galaxy A13 (4GB RAM + 128GB),14999,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 2 GHz Processor",Octa Core,2 GHz Processor,NaN,"4 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px Display with Water ...",50 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12,NaN
315,317,itel,itel S16 Pro,6990,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.3 GHz Processor",Quad Core,1.3 GHz Processor,NaN,"2 GB RAM, 32 GB inbuilt",4000 mAh Battery,"6.6 inches, 1600 x 720 px Display with Punch Hole",8 MP + 2 MP + 0.3 MP Triple Rear & 8 MP Front ...,"Memory Card Supported, upto 32 GB",Android v10,NaN
496,498,samsung,Samsung Galaxy A15,15990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 64 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 720 x 1600 px Display with Water D...",48 MP + 8 MP + 5 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 1 TB",Android v12,NaN
529,531,samsung,Samsung Galaxy F14,14990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.62 inches, 2408 x 1080 px Display with Punch...",50 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card Supported, upto 1 TB",Android v13,NaN
587,589,samsung,Samsung Galaxy A13 (6GB RAM + 128GB),16499,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 2 GHz Processor",Octa Core,2 GHz Processor,NaN,"6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px Display with Water ...",50 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12,NaN
758,760,ikall,iKall Z19,7999,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.6 GHz Processor",Quad Core,1.6 GHz Processor,NaN,"4 GB RAM, 32 GB inbuilt",5000 mAh Battery,"6.5 inches, 720 x 1600 px Display with Water D...",20 MP Rear & 13 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",Android v11.0,NaN
778,780,tecno,Tecno Spark Go 2022,6249,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 2.2 GHz Processor",Octa Core,2.2 GHz Processor,NaN,"2 GB RAM, 32 GB inbuilt",5000 mAh Battery,"6.51 inches, 720 x 1600 px Display with Water ...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v11,NaN
794,796,itel,itel A56,5490,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.3 GHz Processor",Quad Core,1.3 GHz Processor,NaN,"1 GB RAM, 16 GB inbuilt",4000 mAh Battery,"6 inches, 720 x 1600 px Display",8 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Android v9.0 (Pie),NaN
825,827,samsung,Samsung Galaxy S23 FE 5G,54999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",4500 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Punch ...",64 MP Quad Rear & 32 MP Front Camera,Memory Card Not Supported,Android v12,NaN
826,828,samsung,Samsung Galaxy M51s 5G,24990,72.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"6 GB RAM, 128 GB inbuilt",6000 mAh Battery with Fast Charging,"6.7 inches, 1080 x 2400 px Display with Punch ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12,NaN
875,877,huawei,Huawei Nova Y61,21990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 22.5W Fast Charging,"6.52 inches, 720 x 1600 px Display with Water ...",50 MP + 2 MP Triple Rear & 5 MP Front Camera,Memory Card (Hybrid),EMUI v12,NaN
948,950,samsung,Samsung Galaxy M35,22999,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",6000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12,NaN
949,951,samsung,Samsung Galaxy A05,12990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.5 inches, 720 x 1560 px Display with Water D...",48 MP + 2 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12,NaN
991,993,samsung,Samsung Galaxy A11,9990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 1.8 GHz Processor",Octa Core,1.8 GHz Processor,NaN,"2 GB RAM, 32 GB inbuilt",4000 mAh Battery with 15W Fast Charging,"6.4 inches, 720 x 1560 px Display with Punch Hole",13 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,"Memory Card Supported, upto 512 GB",Android v10,NaN
1005,1007,ikall,iKall Z18,6799,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.3 GHz Processor",Quad Core,1.3 GHz Processor,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.82 inches, 720 x 1560 px Display with Punch ...",20 MP Rear & 13 MP Front Camera,"Memory Card (Hybrid), upto 64 GB",Android v10.0,NaN
1019,1021,samsung,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,Octa Core Processor,Octa Core Processor,NaN,NaN,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12,NaN

In [71]:
x = temp_df.iloc[:,13:16].shift(1,axis=1).values
x

array([[None, 'Octa Core Processor', nan],
       [None, 'Quad Core', ' 1.4\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.6\u2009GHz Processor'],
       [None, 'Octa Core', ' 2\u2009GHz Processor'],
       [None, 'Octa Core', ' 2\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.3\u2009GHz Processor'],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core', ' 2\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.6\u2009GHz Processor'],
       [None, 'Octa Core', ' 2.2\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.3\u2009GHz Processor'],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core Processor', nan],
       [None, 'Octa Core', ' 1.8\u2009GHz Processor'],
       [None, 'Quad Core', ' 1.3\u2009GHz Processor'],
       [None, 'Octa Core Processor', nan]], dtype=object)

In [72]:
df.loc[temp_df.index,temp_df.columns[13:16]] = x

In [73]:
df[df['processor_name'].str.contains('Core',na=False)]

Empty DataFrame
Columns: [index, brand_name, model, price, rating, sim, sim_type, has_3G, has_4G, has_5G, has_nfc, has_irblaster, processor, processor_name, num_cores, processor_speed, ram, battery, display, camera, card, os, processor_type]
Index: []

In [74]:
#change processor type (2 nm) to Mediatek MT6739
df[df['processor_name'] == '(28 nm)']

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,num_cores,processor_speed,ram,battery,display,camera,card,os,processor_type
856,858,samsung,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"(28 nm), Quad Core, 1.5 GHz Processor",(28 nm),Quad Core,1.5 GHz Processor,"1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10,NaN

In [75]:
df.loc[856, 'processor_name'] = 'Mediatek MT6739'

In [76]:
df.loc[856]

index                                                858
brand_name                                       samsung
model                            Samsung Galaxy A01 Core
price                                               4999
rating                                               NaN
sim                       Dual Sim, 3G, 4G, VoLTE, Wi-Fi
sim_type                                        Dual Sim
has_3G                                              True
has_4G                                              True
has_5G                                             False
has_nfc                                            False
has_irblaster                                      False
processor          (28 nm), Quad Core, 1.5 GHz Processor
processor_name                           Mediatek MT6739
num_cores                                      Quad Core
processor_speed                        1.5 GHz Processor
ram                              1 GB RAM, 16 GB inbuilt
battery                                 3000 mAh Battery
display                5.3 inches, 720 x 1480 px Display
camera                     8 MP Rear & 5 MP Front Camera
card                               Memory Card Supported
os                                           Android v10
processor_type                                       NaN
Name: 856, dtype: object

In [77]:
# add new col name processor_brand 
processor_brand = df['processor'].str.split(',').str.get(0).str.split(' ').str.get(0)
df.insert(14,'processor_brand',processor_brand)

In [78]:
df.head(1)

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,display,camera,card,os,processor_type
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,Snapdragon,Octa Core,3.2 GHz Processor,"12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13,NaN

In [79]:
df['num_cores'] = df['num_cores'].str.strip()

In [80]:
df['num_cores'] = df['num_cores'].str.replace('Octa Core Processor','Octa Core')
df['num_cores'] = df['num_cores'].str.replace('Hexa Core Processor','Hexa Core')

In [81]:
df['num_cores'].value_counts()

num_cores
Octa Core    899
Hexa Core     39
Quad Core     36
Name: count, dtype: int64

In [82]:
df['processor_speed'] = df['processor_speed'].str.strip().str.replace('GHz Processor','')

In [83]:
df['processor_speed'] = df['processor_speed'].astype('float')

In [84]:
# now work with processor speed
df['processor_speed'].value_counts()

processor_speed
2.00    146
2.20    135
2.40    128
3.20     94
2.30     86
3.00     53
2.84     36
2.05     28
2.50     23
1.80     23
1.60     20
2.85     19
3.22     18
3.10     15
2.60     14
2.90     13
1.82     10
2.80      9
1.30      9
2.73      9
2.36      8
3.05      8
2.65      5
1.40      5
2.70      5
1.50      4
2.96      3
2.86      3
3.13      2
1.10      1
2.35      1
2.37      1
1.99      1
1.95      1
2.10      1
1.20      1
Name: count, dtype: int64

In [85]:
# Now work with Ram col
ram_cap = df['ram'].str.extract(r'(\d+)').astype('Int64')
# ram_cap.astype('Float64')

In [86]:
df.insert(18,'ram_capacity',ram_cap)

In [87]:
internal_memory = df['ram'].str.split(',').str.get(1)
df.insert(19,'internal_memory',internal_memory)

In [88]:
df.head(1)

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os,processor_type
0,2,oneplus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",Snapdragon 8 Gen2,Snapdragon,Octa Core,3.2,"12 GB RAM, 256 GB inbuilt",12,256 GB inbuilt,5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13,NaN

In [89]:
temp_df = df[df['internal_memory'].str.contains('TB',na=False)]
temp_df

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os,processor_type
290,292,apple,Apple iPhone 14 Pro Max (1TB),182999,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A16, Hexa Core Processor",Bionic A16,Bionic,Hexa Core,NaN,"6 GB RAM, 1 TB inbuilt",6,1 TB inbuilt,4323 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px, 120 Hz Display",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v16,NaN
781,783,apple,Apple iPhone 13 Pro Max (1TB),179900,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",Bionic A15,Bionic,Hexa Core,3.22,"6 GB RAM, 1 TB inbuilt",6,1 TB inbuilt,4352 mAh Battery with Fast Charging,"6.7 inches, 1284 x 2778 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,NaN
814,816,apple,Apple iPhone 14 Pro (1TB),172999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A16, Hexa Core Processor",Bionic A16,Bionic,Hexa Core,NaN,"6 GB RAM, 1 TB inbuilt",6,1 TB inbuilt,3200 mAh Battery with Fast Charging,"6.1 inches, 1179 x 2556 px, 120 Hz Display",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v16,NaN
943,945,samsung,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",Snapdragon 8+ Gen1,Snapdragon,Octa Core,3.20,"12 GB RAM, 1 TB inbuilt",12,1 TB inbuilt,4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Memory Card Not Supported,Android v12,NaN
961,963,apple,Apple iPhone 13 Pro (1TB),147900,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",Bionic A15,Bionic,Hexa Core,3.22,"6 GB RAM, 1 TB inbuilt",6,1 TB inbuilt,3095 mAh Battery with Fast Charging,"6.1 inches, 1170 x 2532 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15.0,NaN

In [90]:
df.loc[temp_df.index,'internal_memory'] = '1000\u2009GB inbuilt'

In [91]:
df['internal_memory'] = df['internal_memory'].str.strip().str.extract(r'(\d+)').astype('Int64')

In [92]:
~df['ram'].str.contains('MB')

0       True
1       True
2       True
3       True
4       True
        ...
1015    True
1016    True
1017    True
1018    True
1019    True
Name: ram, Length: 981, dtype: bool

In [93]:
df[df['ram'].str.contains('MB')]

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os,processor_type
486,488,nokia,Nokia 8000 4G,6899,NaN,"Dual Sim, 3G, 4G, Wi-Fi",Dual Sim,True,True,False,False,False,"Snapdragon 210, Quad Core, 1.1 GHz Processor",Snapdragon 210,Snapdragon,Quad Core,1.1,"512 MB RAM, 4 GB inbuilt",512,4,1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN,NaN
627,629,nokia,Nokia 225 4G,3589,NaN,"Dual Sim, 3G, 4G, VoLTE",Dual Sim,True,True,False,False,False,Unisoc T117,Unisoc T117,Unisoc,NaN,NaN,"64 MB RAM, 128 MB inbuilt",64,128,1150 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",RTOS (Series 30+),NaN

In [94]:
# they are feature phones
df.drop([486,627],inplace=True)

In [95]:
temp_df = df[(df['ram_capacity']>18)]
temp_df

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os,processor_type
439,441,apple,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",Bionic A15,Bionic,Hexa Core,3.22,64 GB inbuilt,64,<NA>,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,NaN
483,485,huawei,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster",Dual Sim,True,True,False,True,True,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",Snapdragon 8+ Gen1,Snapdragon,Octa Core,3.20,512 GB inbuilt,512,<NA>,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0,NaN
762,764,apple,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",Bionic A15,Bionic,Hexa Core,3.22,64 GB inbuilt,64,<NA>,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,NaN

In [96]:
x = temp_df.loc[:,['ram_capacity','internal_memory']].shift(1,axis=1).values
x

array([[<NA>, 64],
       [<NA>, 512],
       [<NA>, 64]], dtype=object)

In [97]:
df.loc[temp_df.index,['ram_capacity','internal_memory']] = x

In [98]:
df.loc[[439,483,762]]

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os,processor_type
439,441,apple,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",Bionic A15,Bionic,Hexa Core,3.22,64 GB inbuilt,<NA>,64,NaN,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,NaN
483,485,huawei,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster",Dual Sim,True,True,False,True,True,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",Snapdragon 8+ Gen1,Snapdragon,Octa Core,3.20,512 GB inbuilt,<NA>,512,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0,NaN
762,764,apple,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",Bionic A15,Bionic,Hexa Core,3.22,64 GB inbuilt,<NA>,64,NaN,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,NaN

In [99]:
df.loc[[439, 483, 762], 'ram_capacity'] = [4, 12, 8]

In [100]:
df['ram_capacity'].isnull().sum()

np.int64(0)

In [101]:
df['ram_capacity'].value_counts()

ram_capacity
8     340
6     234
4     216
12     86
3      54
2      31
16      9
1       7
18      2
Name: count, dtype: Int64

In [102]:
battery_capacity = df['battery'].str.strip().str.extract(r'(\d+)')
battery_capacity

         0
0     5000
1     5000
2     5000
3     5000
4     5000
...    ...
1015  5000
1016  5000
1017  5080
1018  5000
1019  5000

[979 rows x 1 columns]

In [103]:
df.insert(21,'battery_capacity',battery_capacity)

In [104]:
has_fast_charging = df['battery'].str.contains('Fast Charging')
df.insert(22,'has_fast_charging',has_fast_charging)

In [105]:
fast_charging_watt = df['battery'].str.split('with ').str.get(1).str.split('W').str.get(0)
df.insert(23,'fast_charging_watt',fast_charging_watt)

In [106]:
temp_df = df[df['fast_charging_watt']=='Fast Charging']
temp_df

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,battery_capacity,has_fast_charging,fast_charging_watt,display,camera,card,os,processor_type
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with Fast Charging,5000,True,Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12,NaN
6,8,apple,Apple iPhone 14,65999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",Bionic A15,Bionic,Hexa Core,3.22,"6 GB RAM, 128 GB inbuilt",6,128,3279 mAh Battery with Fast Charging,3279,True,Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v16,NaN
15,17,apple,Apple iPhone 13,62999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A15, Hexa Core, 3.22 GHz Processor",Bionic A15,Bionic,Hexa Core,3.22,"4 GB RAM, 128 GB inbuilt",4,128,3240 mAh Battery with Fast Charging,3240,True,Fast Charging,"6.1 inches, 1170 x 2532 px Display with Small ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v15,NaN
25,27,samsung,Samsung Galaxy S20 FE 5G,31239,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 865, Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,Octa Core,2.84,"8 GB RAM, 128 GB inbuilt",8,128,4500 mAh Battery with Fast Charging,4500,True,Fast Charging,"6.5 inches, 1080 x 2400 px, 120 Hz Display wit...",12 MP + 12 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card (Hybrid),Android v10,NaN
27,29,apple,Apple iPhone 14 Pro Max,129990,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Bionic A16, Hexa Core Processor",Bionic A16,Bionic,Hexa Core,NaN,"6 GB RAM, 128 GB inbuilt",6,128,4323 mAh Battery with Fast Charging,4323,True,Fast Charging,"6.7 inches, 1290 x 2796 px, 120 Hz Display",48 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v16,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,991,sharp,Sharp Aquos R5G,59990,88.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,"Snapdragon 865, Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,Octa Core,2.84,"12 GB RAM, 256 GB inbuilt",12,256,3730 mAh Battery with Fast Charging,3730,True,Fast Charging,"6.5 inches, 1440 x 3168 px Display with Water ...",48 MP + 12.2 MP + 12.2 MP Triple Rear & 16 MP ...,"Memory Card (Hybrid), upto 1 TB",Android v10,NaN
990,992,huawei,Huawei Mate 30 RS Porsche Design,214990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",Dual Sim,True,True,True,True,True,"Kirin 990, Octa Core, 2.86 GHz Processor",Kirin 990,Kirin,Octa Core,2.86,"12 GB RAM, 512 GB inbuilt",12,512,4500 mAh Battery with Fast Charging,4500,True,Fast Charging,"6.53 inches, 1176 x 2400 px Display with Large...",40 MP Quad Rear & 32 MP Dual Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v10,NaN
994,996,samsung,Samsung Galaxy A9 Pro (2019),39990,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,"Snapdragon 710, Octa Core, 2.2 GHz Processor",Snapdragon 710,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,3400 mAh Battery with Fast Charging,3400,True,Fast Charging,"6.4 inches, 1080 x 2340 px Display with Punch ...",24 MP + 10 MP + 5 MP Triple Rear & 24 MP Front...,"Memory Card Supported, upto 512 GB",Android v9.0 (Pie),NaN
1018,1020,motorola,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with Fast Charging,5000,True,Fast Charging,"6.8 inches, 1080 x 2400 px Display with Punch ...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 1 TB",Android v12,NaN
1019,1021,samsung,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,Octa Core Processor,None,Octa,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8,128,5000 mAh Battery with Fast Charging,5000,True,Fast Charging,"6.5 inches, 1080 x 2400 px Display with Water ...",64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,"Memory Card Supported, upto 1 TB",Android v12,NaN

In [107]:
df.loc[temp_df.index,'fast_charging_watt'] = np.nan

In [108]:
temp_df = df[~df['battery'].str.contains('Fast Charging')]
temp_df

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,battery_capacity,has_fast_charging,fast_charging_watt,display,camera,card,os,processor_type
33,35,apple,Apple iPhone 11,38999,73.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,"A13 Bionic, Hexa Core, 2.65 GHz Processor",A13 Bionic,A13,Hexa Core,2.65,"4 GB RAM, 64 GB inbuilt",4,64,3110 mAh Battery,3110,False,NaN,"6.1 inches, 828 x 1792 px Display with Large N...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v13,NaN
47,49,realme,Realme C33,8950,64.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Unisoc T612, Octa Core, 1.8 GHz Processor",Unisoc T612,Unisoc,Octa Core,1.80,"3 GB RAM, 32 GB inbuilt",3,32,5000 mAh Battery,5000,False,NaN,"6.5 inches, 720 x 1600 px Display with Water D...",50 MP + 0.3 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12,NaN
70,72,oppo,OPPO A17K,9499,62.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Helio G35, Octa Core, 2.3 GHz Processor",Helio G35,Helio,Octa Core,2.30,"3 GB RAM, 64 GB inbuilt",3,64,5000 mAh Battery,5000,False,NaN,"6.56 inches, 720 x 1612 px Display with Water ...",8 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12,NaN
75,77,gionee,Gionee G13 Pro,6190,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Tiger T310, Quad Core, 2 GHz Processor",Tiger T310,Tiger,Quad Core,2.00,"4 GB RAM, 32 GB inbuilt",4,32,3500 mAh Battery,3500,False,NaN,"6.26 inches, 720 x 1600 px Display with Large ...",13 MP Dual Rear & 5 MP Front Camera,Memory Card Supported,HarmonyOS v2,NaN
79,81,xiaomi,Xiaomi Redmi 10A (4GB RAM + 64GB),8388,66.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Helio G25, Octa Core, 2 GHz Processor",Helio G25,Helio,Octa Core,2.00,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery,5000,False,NaN,"6.53 inches, 720 x 1600 px Display with Water ...",13 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 512 GB",Android v11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,999,poco,Poco C55,7999,70.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Helio G85, Octa Core, 2 GHz Processor",Helio G85,Helio,Octa Core,2.00,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery,5000,False,NaN,"6.71 inches, 720 x 1650 px Display with Water ...",50 MP + Depth Sensor Dual Rear & 5 MP Front Ca...,"Memory Card Supported, upto 512 GB",Android v12,NaN
1003,1005,lava,Lava X3,6999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Helio A22, Quad Core, 2 GHz Processor",Helio A22,Helio,Quad Core,2.00,"3 GB RAM, 32 GB inbuilt",3,32,4000 mAh Battery,4000,False,NaN,"6.5 inches, 1600 x 720 px Display with Water D...",8 MP Dual Rear & 5 MP Front Camera,"Memory Card (Hybrid), upto 512 GB",Android v12,NaN
1005,1007,ikall,iKall Z18,6799,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.3 GHz Processor",None,Quad,Quad Core,1.30,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery,5000,False,NaN,"6.82 inches, 720 x 1560 px Display with Punch ...",20 MP Rear & 13 MP Front Camera,"Memory Card (Hybrid), upto 64 GB",Android v10.0,NaN
1006,1008,oukitel,Oukitel WP9,25899,72.0,"Dual Sim, 3G, 4G, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,"Helio P60, Octa Core, 2 GHz Processor",Helio P60,Helio,Octa Core,2.00,"6 GB RAM, 128 GB inbuilt",6,128,8000 mAh Battery,8000,False,NaN,"5.86 inches, 720 x 1520 px Display with Large ...",16 MP + 13 MP + 13 MP Triple Rear & 8 MP Front...,Memory Card Supported,Android v10,NaN
1012,1014,itel,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi",Dual Sim,True,True,False,False,False,"Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor",Spreadtrum SC9832E,Spreadtrum,Quad Core,1.40,"2 GB RAM, 32 GB inbuilt",2,32,3020 mAh Battery,3020,False,NaN,"5 inches, 854 x 480 px Display",2 MP Rear Camera,Memory Card Not Supported,Android v11,NaN

In [109]:
df.loc[temp_df.index,'fast_charging_watt'] = '0'

In [110]:
df['battery_capacity'] = df['battery_capacity'].astype('Int64')
df['fast_charging_watt'] = df['fast_charging_watt'].astype('Float64')

In [111]:
display_size = df['display'].str.strip().str.split(' ').str.get(0).astype(float)
display_size

0       6.70
1       6.59
2       6.60
3       6.55
4       6.70
        ...
1015    6.67
1016    6.50
1017    6.60
1018    6.80
1019    6.50
Name: display, Length: 979, dtype: float64

In [112]:

resolution = df['display'].str.split(',').str.get(1).str.strip().str.split('px').str.get(0).str.strip()
resolution

0       1440 x 3216
1       1080 x 2412
2       1080 x 2408
3       1080 x 2400
4       1080 x 2412
           ...
1015    1080 x 2460
1016     720 x 1600
1017    1080 x 2460
1018    1080 x 2400
1019    1080 x 2400
Name: display, Length: 979, dtype: object

In [113]:
refresh_rate = df['display'].str.split(',').str.get(2).str.split('Hz').str.get(0).str.strip().apply(lambda x: 60 if pd.isna(x) else x).astype(int)
refresh_rate

0       120
1       120
2        90
3       120
4       120
       ...
1015    120
1016     60
1017    144
1018     60
1019     60
Name: display, Length: 979, dtype: int64

In [114]:
notch_type = df['display'].str.split('with').str.get(1).str.strip().apply(lambda x: 'Not specified' if pd.isna(x) else x)
notch_type

0             Punch Hole
1             Punch Hole
2       Water Drop Notch
3             Punch Hole
4             Punch Hole
              ...
1015          Punch Hole
1016    Water Drop Notch
1017          Punch Hole
1018          Punch Hole
1019    Water Drop Notch
Name: display, Length: 979, dtype: str

In [115]:
df.insert(25,'display_size',display_size)
df.insert(26,'resolution',resolution)
df.insert(27,'refresh_rate',refresh_rate)
df.insert(28,'notch_type',notch_type)

In [116]:
def extract_num_camera(text):
    if 'Quad' in text:
        return 4
    elif 'Triple' in text:
        return 3
    elif 'Dual' in text:
        return 2
    else:
        return 1

In [117]:
# work with camera cols
nums_rear_cameras = df['camera'].str.split('&').str.get(0).apply(extract_num_camera)
nums_rear_cameras

0       3
1       3
2       3
3       3
4       3
       ..
1015    3
1016    3
1017    3
1018    3
1019    3
Name: camera, Length: 979, dtype: int64

In [118]:
def Extract_num_camera(text):
    if 'Dual' in text:
        return '2'
    elif 'Missing' in text:
        return 'Missing'
    else:
        return '1'

In [119]:
nums_front_cameras = df['camera'].str.split('&').str.get(1).fillna('Missing').apply(Extract_num_camera)
nums_front_cameras

0       1
1       1
2       1
3       1
4       1
       ..
1015    1
1016    1
1017    1
1018    1
1019    1
Name: camera, Length: 979, dtype: str

In [120]:
camera_spec =  df['camera'].str.strip()
camera_spec

0       50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...
1       64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...
2       50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...
3       50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...
4       108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...
                              ...
1015    64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...
1016    48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...
1017    64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...
1018    108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...
1019    64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...
Name: camera, Length: 979, dtype: str

In [121]:
df.insert(30,'camera_spec',camera_spec)
df.insert(31,'nums_rear_cameras',nums_rear_cameras)

In [122]:
df.insert(32,'nums_front_cameras',nums_front_cameras)

In [123]:
df[df['nums_front_cameras']=='Missing']

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,battery_capacity,has_fast_charging,fast_charging_watt,display,display_size,resolution,refresh_rate,notch_type,camera,camera_spec,nums_rear_cameras,nums_front_cameras,card,os,processor_type
69,71,oppo,Oppo Find N Fold,99990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",Snapdragon 8+ Gen1,Snapdragon,Octa Core,3.20,"8 GB RAM, 256 GB inbuilt",8,256,5000 mAh Battery with 67W Fast Charging,5000,True,67.0,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",7.10,1792 x 1920,120,Punch Hole,"Foldable Display, Dual Display","Foldable Display, Dual Display",2,Missing,Memory Card Not Supported,Android v12,NaN
462,464,xiaomi,Xiaomi Mi Mix Alpha,199990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Snapdragon 855+, Octa Core, 2.96 GHz Processor",Snapdragon 855+,Snapdragon,Octa Core,2.96,"12 GB RAM, 512 GB inbuilt",12,512,4050 mAh Battery with 40W Fast Charging,4050,True,40.0,"7.92 inches, 2088 x 2250 px Display",7.92,2088 x 2250,60,Not specified,108 MP + 20 MP + 12 MP Triple Rear Camera,108 MP + 20 MP + 12 MP Triple Rear Camera,3,Missing,Memory Card Not Supported,Android v10,NaN
993,995,huawei,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",Dual Sim,True,True,True,True,True,"Kirin 990, Octa Core, 2.86 GHz Processor",Kirin 990,Kirin,Octa Core,2.86,"8 GB RAM, 512 GB inbuilt",8,512,4500 mAh Battery with 55W Fast Charging,4500,True,55.0,"8 inches, 2200 x 2480 px Display",8.00,2200 x 2480,60,Not specified,48 MP Quad Rear Camera,48 MP Quad Rear Camera,4,Missing,"Memory Card (Hybrid), upto 256 GB",NaN,NaN
1012,1014,itel,itel A23s,4787,NaN,"Dual Sim, 3G, 4G, Wi-Fi",Dual Sim,True,True,False,False,False,"Spreadtrum SC9832E, Quad Core, 1.4 GHz Processor",Spreadtrum SC9832E,Spreadtrum,Quad Core,1.40,"2 GB RAM, 32 GB inbuilt",2,32,3020 mAh Battery,3020,False,0.0,"5 inches, 854 x 480 px Display",5.00,854 x 480,60,Not specified,2 MP Rear Camera,2 MP Rear Camera,1,Missing,Memory Card Not Supported,Android v11,NaN

In [124]:
df.loc[[462,993,1012,69],'nums_front_cameras'] = ['0','0','1','2']

In [125]:
df['nums_front_cameras'] = df['nums_front_cameras'].astype(int)

In [126]:
def card_type(text):
    if 'Memory Card Supported' in text:
        return 'supported'
    elif 'Memory Card Not Supported' in text:
        return 'not supported'
    else:
        return 'hybrid'

In [127]:
# working with card col
card_type = df['card'].str.split(',').str.get(0).str.strip().apply(card_type)
card_type

0       not supported
1              hybrid
2           supported
3              hybrid
4       not supported
            ...
1015    not supported
1016        supported
1017    not supported
1018        supported
1019        supported
Name: card, Length: 979, dtype: str

In [128]:
card_size = df['card'].str.split(',').str.get(1).str.strip().str.extract(r'(\d+)', expand=False)
card_size

0       NaN
1         1
2         1
3         1
4       NaN
       ...
1015    NaN
1016      1
1017    NaN
1018      1
1019      1
Name: card, Length: 979, dtype: object

In [129]:
df.insert(34,'card_type',card_type)
df.insert(35,'card_size',card_size)

In [130]:
temp_df = df[(df['card_size']=='1') | (df['card_size']=='1000')]
temp_df

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,battery_capacity,has_fast_charging,fast_charging_watt,display,display_size,resolution,refresh_rate,notch_type,camera,camera_spec,nums_rear_cameras,nums_front_cameras,card,card_type,card_size,os,processor_type
1,3,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with 33W Fast Charging,5000,True,33.0,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",6.59,1080 x 2412,120,Punch Hole,64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,3,1,"Memory Card (Hybrid), upto 1 TB",hybrid,1,Android v12,NaN
2,4,samsung,Samsung Galaxy A14 5G,16499,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Exynos 1330, Octa Core, 2.4 GHz Processor",Exynos 1330,Exynos,Octa Core,2.40,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery with 15W Fast Charging,5000,True,15.0,"6.6 inches, 1080 x 2408 px, 90 Hz Display with...",6.60,1080 x 2408,90,Water Drop Notch,50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front ...,3,1,"Memory Card Supported, upto 1 TB",supported,1,Android v13,NaN
3,5,motorola,Motorola Moto G62 5G,14999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with Fast Charging,5000,True,<NA>,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",6.55,1080 x 2400,120,Punch Hole,50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,3,1,"Memory Card (Hybrid), upto 1 TB",hybrid,1,Android v12,NaN
5,7,samsung,Samsung Galaxy F23 5G (6GB RAM + 128GB),16999,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 750G, Octa Core, 2.2 GHz Processor",Snapdragon 750G,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with 25W Fast Charging,5000,True,25.0,"6.6 inches, 1080 x 2408 px, 120 Hz Display wit...",6.60,1080 x 2408,120,Water Drop Notch,50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front C...,50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front C...,3,1,"Memory Card Supported, upto 1 TB",supported,1,Android v12,NaN
10,12,realme,Realme 10 Pro,18999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with 33W Fast Charging,5000,True,33.0,"6.72 inches, 1080 x 2400 px, 120 Hz Display wi...",6.72,1080 x 2400,120,Punch Hole,108 MP + 2 MP Dual Rear & 16 MP Front Camera,108 MP + 2 MP Dual Rear & 16 MP Front Camera,2,1,"Memory Card Supported, upto 1 TB",supported,1,Android v13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002,1004,doogee,Doogee S99,14999,84.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,"Helio G96, Octa Core, 2.05 GHz Processor",Helio G96,Helio,Octa Core,2.05,"8 GB RAM, 128 GB inbuilt",8,128,6000 mAh Battery with 33W Fast Charging,6000,True,33.0,"6.3 inches, 1080 x 2340 px Display with Water ...",6.30,1080 x 2340,60,Water Drop Notch,108 MP + 64 MP + 16 MP Triple Rear & 32 MP Fro...,108 MP + 64 MP + 16 MP Triple Rear & 32 MP Fro...,3,1,"Memory Card Supported, upto 1 TB",supported,1,Android v12,NaN
1010,1012,realme,Realme Narzo 50i Prime (4GB RAM + 64GB),8720,64.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Tiger T612, Octa Core, 1.82 GHz Processor",Tiger T612,Tiger,Octa Core,1.82,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery with 10W Fast Charging,5000,True,10.0,"6.5 inches, 720 x 1600 px Display with Water D...",6.50,720 x 1600,60,Water Drop Notch,8 MP Rear & 5 MP Front Camera,8 MP Rear & 5 MP Front Camera,1,1,"Memory Card Supported, upto 1 TB",supported,1,Android v11,NaN
1016,1018,honor,Honor X8 5G,14990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Snapdragon 480+, Octa Core, 2.2 GHz Processor",Snapdragon 480+,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with 22.5W Fast Charging,5000,True,22.5,"6.5 inches, 720 x 1600 px Display with Water D...",6.50,720 x 1600,60,Water Drop Notch,48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,48 MP + 2 MP + Depth Sensor Triple Rear & 8 MP...,3,1,"Memory Card Supported, upto 1 TB",supported,1,Android v11,NaN
1018,1020,motorola,Motorola Moto G91 5G,19990,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 695, Octa Core, 2.2 GHz Processor",Snapdragon 695,Snapdragon,Octa Core,2.20,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with Fast Charging,5000,True,<NA>,"6.8 inches, 1080 x 2400 px Display with Punch ...",6.80,1080 x 2400,60,Punch Hole,108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,3,1,"Memory Card Supported, upto 1 TB",supported,1,Android v12,NaN
1019,1021,samsung,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,Octa Core Processor,None,Octa,Octa Core,NaN,"8 GB RAM, 128 GB inbuilt",8,128,5000 mAh Battery with Fast Charging,5000,True,<NA>,"6.5 inches, 1080 x 2400 px Display with Water ...",6.50,1080 x 2400,60,Water Drop Notch,64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,3,1,"Memory Card Supported, upto 1 TB",supported,1,Android v12,NaN

In [131]:
df.loc[temp_df.index,'card_size'] = '1024'

In [132]:
# working on os cols
os_name = df['os'].str.split(' ').str.get(0).str.strip()
os_name

0       Android
1       Android
2       Android
3       Android
4       Android
         ...
1015    Android
1016    Android
1017    Android
1018    Android
1019    Android
Name: os, Length: 979, dtype: object

In [133]:
os_version = df['os'].str.split(' ').str.get(1).str.strip('v').str.strip()
os_version

0       13
1       12
2       13
3       12
4       13
        ..
1015    12
1016    11
1017    12
1018    12
1019    12
Name: os, Length: 979, dtype: object

In [134]:
df.insert(37,'os_name',os_name)
df.insert(38,'os_version',os_version)

In [135]:
def num_of_cores(text):
    if 'Quad Core' in text:
        return 4
    elif 'Octa Core' in text:
        return 8
    else:
        return 6

In [136]:
df.loc[[152,263,282,429,448,728],'num_cores'] = ['6','6','6','8','6','6']

In [137]:
df['num_cores'] = df['num_cores'].apply(num_of_cores)

In [138]:
print(df['processor_brand'].value_counts().to_string())

processor_brand
Snapdragon    403
Helio         201
Dimensity     177
Exynos         49
Bionic         39
Unisoc         26
Tiger          24
Octa           14
Google          9
Kirin           7
Quad            6
A13             5
                4
Qualcomm        4
Spreadtrum      4
SC9863A         2
Apple           1
Sanpdragon      1
Fusion          1
(28             1
Samsung         1

In [139]:
df['processor_brand'] = df['processor_name'].str.split(' ').str.get(0)

In [140]:
temp_df = df[df['processor_name'].isna()]
temp_df

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,battery_capacity,has_fast_charging,fast_charging_watt,display,display_size,resolution,refresh_rate,notch_type,camera,camera_spec,nums_rear_cameras,nums_front_cameras,card,card_type,card_size,os,os_name,os_version,processor_type
118,120,tesla,Tesla Pi Phone,69999,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,Octa Core Processor,None,None,8,NaN,"16 GB RAM, 512 GB inbuilt",16,512,5000 mAh Battery with 120W Fast Charging,5000,True,120.0,"6.73 inches, 1080 x 2448 px, 165 Hz Display",6.73,1080 x 2448,165,Not specified,50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,3,1,Memory Card Not Supported,not supported,NaN,Android v13,Android,13,NaN
143,145,jio,Jio Phone 3,4499,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.4 GHz Processor",None,None,4,1.4,"2 GB RAM, 64 GB inbuilt",2,64,2800 mAh Battery,2800,False,0.0,"5 inches, 720 x 1280 px Display",5.00,720 x 1280,60,Not specified,5 MP Rear & 2 MP Front Camera,5 MP Rear & 2 MP Front Camera,1,1,"Memory Card Supported, upto 128 GB",supported,128,Android v8.1 (Oreo),Android,8.1,NaN
188,190,ikall,iKall Z19 Pro,8099,60.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.6 GHz Processor",None,None,4,1.6,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery,5000,False,0.0,"6.5 inches, 720 x 1600 px Display with Water D...",6.50,720 x 1600,60,Water Drop Notch,13 MP Rear & 8 MP Front Camera,13 MP Rear & 8 MP Front Camera,1,1,"Memory Card (Hybrid), upto 128 GB",hybrid,128,Android v11.0,Android,11.0,NaN
201,203,samsung,Samsung Galaxy A13,14450,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 2 GHz Processor",None,None,8,2.0,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery with 25W Fast Charging,5000,True,25.0,"6.6 inches, 1080 x 2408 px Display with Water ...",6.60,1080 x 2408,60,Water Drop Notch,50 MP Quad Rear & 8 MP Front Camera,50 MP Quad Rear & 8 MP Front Camera,4,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v12,Android,12,NaN
309,311,samsung,Samsung Galaxy A13 (4GB RAM + 128GB),14999,75.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 2 GHz Processor",None,None,8,2.0,"4 GB RAM, 128 GB inbuilt",4,128,5000 mAh Battery with 25W Fast Charging,5000,True,25.0,"6.6 inches, 1080 x 2408 px Display with Water ...",6.60,1080 x 2408,60,Water Drop Notch,50 MP Quad Rear & 8 MP Front Camera,50 MP Quad Rear & 8 MP Front Camera,4,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v12,Android,12,NaN
315,317,itel,itel S16 Pro,6990,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.3 GHz Processor",None,None,4,1.3,"2 GB RAM, 32 GB inbuilt",2,32,4000 mAh Battery,4000,False,0.0,"6.6 inches, 1600 x 720 px Display with Punch Hole",6.60,1600 x 720,60,Punch Hole,8 MP + 2 MP + 0.3 MP Triple Rear & 8 MP Front ...,8 MP + 2 MP + 0.3 MP Triple Rear & 8 MP Front ...,3,1,"Memory Card Supported, upto 32 GB",supported,32,Android v10,Android,10,NaN
496,498,samsung,Samsung Galaxy A15,15990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,Octa Core Processor,None,None,8,NaN,"6 GB RAM, 64 GB inbuilt",6,64,5000 mAh Battery with Fast Charging,5000,True,<NA>,"6.5 inches, 720 x 1600 px Display with Water D...",6.50,720 x 1600,60,Water Drop Notch,48 MP + 8 MP + 5 MP Triple Rear & 8 MP Front C...,48 MP + 8 MP + 5 MP Triple Rear & 8 MP Front C...,3,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v12,Android,12,NaN
529,531,samsung,Samsung Galaxy F14,14990,67.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,Octa Core Processor,None,None,8,NaN,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery with 25W Fast Charging,5000,True,25.0,"6.62 inches, 2408 x 1080 px Display with Punch...",6.62,2408 x 1080,60,Punch Hole,50 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...,50 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...,3,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v13,Android,13,NaN
587,589,samsung,Samsung Galaxy A13 (6GB RAM + 128GB),16499,78.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 2 GHz Processor",None,None,8,2.0,"6 GB RAM, 128 GB inbuilt",6,128,5000 mAh Battery with 25W Fast Charging,5000,True,25.0,"6.6 inches, 1080 x 2408 px Display with Water ...",6.60,1080 x 2408,60,Water Drop Notch,50 MP Quad Rear & 8 MP Front Camera,50 MP Quad Rear & 8 MP Front Camera,4,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v12,Android,12,NaN
758,760,ikall,iKall Z19,7999,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.6 GHz Processor",None,None,4,1.6,"4 GB RAM, 32 GB inbuilt",4,32,5000 mAh Battery,5000,False,0.0,"6.5 inches, 720 x 1600 px Display with Water D...",6.50,720 x 1600,60,Water Drop Notch,20 MP Rear & 13 MP Front Camera,20 MP Rear & 13 MP Front Camera,1,1,"Memory Card (Hybrid), upto 128 GB",hybrid,128,Android v11.0,Android,11.0,NaN
778,780,tecno,Tecno Spark Go 2022,6249,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 2.2 GHz Processor",None,None,8,2.2,"2 GB RAM, 32 GB inbuilt",2,32,5000 mAh Battery,5000,False,0.0,"6.51 inches, 720 x 1600 px Display with Water ...",6.51,720 x 1600,60,Water Drop Notch,13 MP + 2 MP Dual Rear & 8 MP Front Camera,13 MP + 2 MP Dual Rear & 8 MP Front Camera,2,1,"Memory Card Supported, upto 256 GB",supported,256,Android v11,Android,11,NaN
794,796,itel,itel A56,5490,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.3 GHz Processor",None,None,4,1.3,"1 GB RAM, 16 GB inbuilt",1,16,4000 mAh Battery,4000,False,0.0,"6 inches, 720 x 1600 px Display",6.00,720 x 1600,60,Not specified,8 MP Dual Rear & 5 MP Front Camera,8 MP Dual Rear & 5 MP Front Camera,2,1,"Memory Card Supported, upto 32 GB",supported,32,Android v9.0 (Pie),Android,9.0,NaN
825,827,samsung,Samsung Galaxy S23 FE 5G,54999,77.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,Octa Core Processor,None,None,8,NaN,"8 GB RAM, 128 GB inbuilt",8,128,4500 mAh Battery with Fast Charging,4500,True,<NA>,"6.5 inches, 1080 x 2400 px Display with Punch ...",6.50,1080 x 2400,60,Punch Hole,64 MP Quad Rear & 32 MP Front Camera,64 MP Quad Rear & 32 MP Front Camera,4,1,Memory Card Not Supported,not supported,NaN,Android v12,Android,12,NaN
826,828,samsung,Samsung Galaxy M51s 5G,24990,72.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,Octa Core Processor,None,None,8,NaN,"6 GB RAM, 128 GB inbuilt",6,128,6000 mAh Battery with Fast Charging,6000,True,<NA>,"6.7 inches, 1080 x 2400 px Display with Punch ...",6.70,1080 x 2400,60,Punch Hole,64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,3,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v12,Android,12,NaN
875,877,huawei,Huawei Nova Y61,21990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,Octa Core Processor,None,None,8,NaN,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery with 22.5W Fast Charging,5000,True,22.5,"6.52 inches, 720 x 1600 px Display with Water ...",6.52,720 x 1600,60,Water Drop Notch,50 MP + 2 MP Triple Rear & 5 MP Front Camera,50 MP + 2 MP Triple Rear & 5 MP Front Camera,3,1,Memory Card (Hybrid),hybrid,NaN,EMUI v12,EMUI,12,NaN
948,950,samsung,Samsung Galaxy M35,22999,74.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,False,True,False,Octa Core Processor,None,None,8,NaN,"8 GB RAM, 128 GB inbuilt",8,128,6000 mAh Battery with Fast Charging,6000,True,<NA>,"6.5 inches, 1080 x 2400 px Display with Water ...",6.50,1080 x 2400,60,Water Drop Notch,64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,3,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v12,Android,12,NaN
949,951,samsung,Samsung Galaxy A05,12990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,Octa Core Processor,None,None,8,NaN,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery with 18W Fast Charging,5000,True,18.0,"6.5 inches, 720 x 1560 px Display with Water D...",6.50,720 x 1560,60,Water Drop Notch,48 MP + 2 MP Dual Rear & 5 MP Front Camera,48 MP + 2 MP Dual Rear & 5 MP Front Camera,2,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v12,Android,12,NaN
991,993,samsung,Samsung Galaxy A11,9990,63.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Octa Core, 1.8 GHz Processor",None,None,8,1.8,"2 GB RAM, 32 GB inbuilt",2,32,4000 mAh Battery with 15W Fast Charging,4000,True,15.0,"6.4 inches, 720 x 1560 px Display with Punch Hole",6.40,720 x 1560,60,Punch Hole,13 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,13 MP + 5 MP + 2 MP Triple Rear & 8 MP Front C...,3,1,"Memory Card Supported, upto 512 GB",supported,512,Android v10,Android,10,NaN
1005,1007,ikall,iKall Z18,6799,61.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Quad Core, 1.3 GHz Processor",None,None,4,1.3,"4 GB RAM, 64 GB inbuilt",4,64,5000 mAh Battery,5000,False,0.0,"6.82 inches, 720 x 1560 px Display with Punch ...",6.82,720 x 1560,60,Punch Hole,20 MP Rear & 13 MP Front Camera,20 MP Rear & 13 MP Front Camera,1,1,"Memory Card (Hybrid), upto 64 GB",hybrid,64,Android v10.0,Android,10.0,NaN
1019,1021,samsung,Samsung Galaxy M52s 5G,24990,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,Octa Core Processor,None,None,8,NaN,"8 GB RAM, 128 GB inbuilt",8,128,5000 mAh Battery with Fast Charging,5000,True,<NA>,"6.5 inches, 1080 x 2400 px Display with Water ...",6.50,1080 x 2400,60,Water Drop Notch,64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front ...,3,1,"Memory Card Supported, upto 1 TB",supported,1024,Android v12,Android,12,NaN

In [141]:
df.loc[temp_df.index,'processor_name'] = ['Unknown','Snapdragon 215','Unknown','Exynos 850','Exynos 850','Unisoc SC9863A','Helio G99','Exynos 1330','Exynos 850','Unknown','Unisoc SC9863A','Unisoc SC7731E','Exynos 2200','Snapdragon 778G','Kirin 710A','Exynos 1380','Helio G85','Snapdragon 450','Unknown','Snapdragon 778G'
]

In [142]:
df['processor_brand'] = df['processor_name'].str.split(' ').str.get(0)

In [143]:
df.loc[temp_df.index,'processor_brand'] = np.nan

In [144]:
temp_df = df[df['os_name'].isna()]
temp_df

,index,brand_name,model,price,rating,sim,sim_type,has_3G,has_4G,has_5G,has_nfc,has_irblaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,battery_capacity,has_fast_charging,fast_charging_watt,display,display_size,resolution,refresh_rate,notch_type,camera,camera_spec,nums_rear_cameras,nums_front_cameras,card,card_type,card_size,os,os_name,os_version,processor_type
159,161,oppo,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",Snapdragon 8+ Gen1,Snapdragon,8,3.20,"12 GB RAM, 256 GB inbuilt",12,256,4520 mAh Battery with 67W Fast Charging,4520,True,67.0,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",7.10,1792 x 1920,120,Punch Hole,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,3,2,Memory Card Not Supported,not supported,NaN,NaN,NaN,NaN,NaN
306,308,samsung,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Single Sim,True,True,True,True,False,"Snapdragon 888, Octa Core, 2.84 GHz Processor",Snapdragon 888,Snapdragon,8,2.84,"8 GB RAM, 128 GB inbuilt",8,128,3300 mAh Battery with 15W Fast Charging,3300,True,15.0,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",6.70,1080 x 2640,120,Punch Hole,12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,2,1,Memory Card Not Supported,not supported,NaN,NaN,NaN,NaN,NaN
322,324,royole,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Snapdragon 865, Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,8,2.84,"8 GB RAM, 128 GB inbuilt",8,128,4450 mAh Battery,4450,False,0.0,"7.8 inches, 1440 x 1920 px Display",7.80,1440 x 1920,60,Not specified,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,3,1,"Memory Card Supported, upto 256 GB",supported,256,NaN,NaN,NaN,NaN
365,367,oppo,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Single Sim,True,True,True,True,False,"Dimensity 9000, Octa Core, 3.05 GHz Processor",Dimensity 9000,Dimensity,8,3.05,"8 GB RAM, 128 GB inbuilt",8,128,4300 mAh Battery with 44W Fast Charging,4300,True,44.0,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",6.80,1200 x 2400,120,Punch Hole,50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,2,1,Memory Card Not Supported,not supported,NaN,NaN,NaN,NaN,NaN
392,394,oppo,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Single Sim,True,True,True,True,False,"Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor",Dimensity 9000 Plus,Dimensity,8,3.20,"8 GB RAM, 256 GB inbuilt",8,256,4300 mAh Battery with 44W Fast Charging,4300,True,44.0,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",6.80,1080 x 2520,120,Punch Hole,50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,2,1,Memory Card Not Supported,not supported,NaN,NaN,NaN,NaN,NaN
504,506,samsung,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",Snapdragon 8+ Gen1,Snapdragon,8,3.20,"8 GB RAM, 128 GB inbuilt",8,128,3700 mAh Battery with 25W Fast Charging,3700,True,25.0,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",6.70,1080 x 2640,120,Punch Hole,12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,2,1,Memory Card Not Supported,not supported,NaN,NaN,NaN,NaN,NaN
570,572,lg,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 765G , Octa Core, 2.4 GHz Processor",Snapdragon 765G,Snapdragon,8,2.40,"8 GB RAM, 128 GB inbuilt",8,128,4000 mAh Battery with Fast Charging,4000,True,<NA>,"6.8 inches, 1080 x 2460 px Display",6.80,1080 x 2460,60,Not specified,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,3,1,"Memory Card (Hybrid), upto 2 TB",hybrid,2,NaN,NaN,NaN,NaN
613,615,oukitel,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",Dual Sim,True,True,False,False,False,"Helio G99, Octa Core, 2.2 GHz Processor",Helio G99,Helio,8,2.20,"12 GB RAM, 256 GB inbuilt",12,256,9800 mAh Battery with 66W Fast Charging,9800,True,66.0,"6.78 inches, 1080 x 2400 px, 120 Hz Display",6.78,1080 x 2400,120,Not specified,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,3,1,Memory Card Not Supported,not supported,NaN,NaN,NaN,NaN,NaN
682,684,lg,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Snapdragon 865, Octa Core, 2.84 GHz Processor",Snapdragon 865,Snapdragon,8,2.84,"8 GB RAM, 128 GB inbuilt",8,128,5000 mAh Battery with Fast Charging,5000,True,<NA>,"6.8 inches, 1080 x 2460 px Display with Punch ...",6.80,1080 x 2460,60,Punch Hole,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,3,1,"Memory Card (Hybrid), upto 2 TB",hybrid,2,NaN,NaN,NaN,NaN
721,723,asus,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Dual Sim,True,True,True,True,False,"Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor",Dimensity 9000 Plus,Dimensity,8,3.20,"16 GB RAM, 512 GB inbuilt",16,512,6000 mAh Battery with 65W Fast Charging,6000,True,65.0,"6.78 inches, 1080 x 2448 px, 165 Hz Display",6.78,1080 x 2448,165,Not specified,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,3,1,Memory Card Not Supported,not supported,NaN,NaN,NaN,NaN,NaN
726,728,huawei,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster",Dual Sim,True,True,False,True,True,"Snapdragon 888, Octa Core, 2.84 GHz Processor",Snapdragon 888,Snapdragon,8,2.84,"8 GB RAM, 512 GB inbuilt",8,512,4600 mAh Battery with 66W Fast Charging,4600,True,66.0,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",7.80,2200 x 2480,120,Punch Hole,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,3,1,"Memory Card (Hybrid), upto 256 GB",hybrid,256,NaN,NaN,NaN,NaN
894,896,royole,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",Dual Sim,True,True,True,False,False,"Snapdragon 888, Octa Core, 2.84 GHz Processor",Snapdragon 888,Snapdragon,8,2.84,"8 GB RAM, 128 GB inbuilt",8,128,3360 mAh Battery,3360,False,0.0,"7.2 inches, 1440 x 1920 px Display",7.20,1440 x 1920,60,Not specified,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,3,1,"Memory Card Supported, upto 256 GB",supported,256,NaN,NaN,NaN,NaN
993,995,huawei,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...",Dual Sim,True,True,True,True,True,"Kirin 990, Octa Core, 2.86 GHz Processor",Kirin 990,Kirin,8,2.86,"8 GB RAM, 512 GB inbuilt",8,512,4500 mAh Battery with 55W Fast Charging,4500,True,55.0,"8 inches, 2200 x 2480 px Display",8.00,2200 x 2480,60,Not specified,48 MP Quad Rear Camera,48 MP Quad Rear Camera,4,0,"Memory Card (Hybrid), upto 256 GB",hybrid,256,NaN,NaN,NaN,NaN

In [145]:
# nan values handeling 
df.loc[temp_df.index,'os'] = ['Android v13', 'Android v11', 'Android v10', 'Android v13', 'Android v13', 'Android v12', 'Android v10', 'Android v12', 'Android v10', 'Android v13', 'HarmonyOS v2.0', 'Android v12', 'Android v9.0']
df.loc[temp_df.index,'os_name'] = ['Android', 'Android', 'Android', 'Android', 'Android', 'Android', 'Android', 'Android', 'Android', 'Android', 'Harmony', 'Android', 'Android']
df.loc[temp_df.index,'os_version'] = ['13', '11', '10', '13', '13', '12', '10', '12', '10', '13', '2', '12', '9']

In [146]:
# 884,942 rows hav nan os_version
df.loc[[884,942],'os_version'] = ['2','12']

In [147]:
df.drop(columns=['sim','processor','ram','battery','display','camera','card','os','processor_type','index'],inplace=True)

In [148]:
# df.to_csv('cleaned_smartphone.csv',index=False)

In [149]:
df.info()

<class 'pandas.DataFrame'>
Index: 979 entries, 0 to 1019
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brand_name          979 non-null    object
 1   model               979 non-null    str
 2   price               979 non-null    int64
 3   rating              879 non-null    float64
 4   sim_type            979 non-null    object
 5   has_3G              979 non-null    bool
 6   has_4G              979 non-null    bool
 7   has_5G              979 non-null    bool
 8   has_nfc             979 non-null    bool
 9   has_irblaster       979 non-null    bool
 10  processor_name      979 non-null    object
 11  processor_brand     959 non-null    object
 12  num_cores           979 non-null    int64
 13  processor_speed     937 non-null    float64
 14  ram_capacity        979 non-null    Int64
 15  internal_memory     979 non-null    Int64
 16  battery_capacity    968 non-null    Int64
 17  has_fast_charging   979 non-null    bool
 18  fast_charging_watt  911 non-null    Float64
 19  display_size        979 non-null    float64
 20  resolution          979 non-null    object
 21  refresh_rate        979 non-null    int64
 22  notch_type          979 non-null    str
 23  camera_spec         979 non-null    str
 24  nums_rear_cameras   979 non-null    int64
 25  nums_front_cameras  979 non-null    int64
 26  card_type           979 non-null    str
 27  card_size           506 non-null    object
 28  os_name             979 non-null    object
 29  os_version          979 non-null    object
dtypes: Float64(1), Int64(3), bool(6), float64(3), int64(5), object(8), str(4)
memory usage: 233.1+ KB